export const UserActionTypes = {
    SET_CURRENT_USER_START: 'SET_CURRENT_USER_START',
    SET_CURRENT_USER_SUCCESS: 'SET_CURRENT_USER_SUCCESS',
    SET_CURRENT_USER_ERROR: 'SET_CURRENT_USER_ERROR',

    LOGOUT_START: 'LOGOUT_START',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_ERROR: 'LOGOUT_ERROR'
};
