export default {
    GET_JOBS: 'GET_JOBS',
    SHOW_JOB_DETAILS: 'SHOW_JOB_DETAILS',
    FETCH_JOBS_START: 'FETCH_JOBS_START',
    FETCH_JOBS_SUCCESS: 'FETCH_JOBS_SUCCESS',
    FETCH_JOBS_FAIL: 'FETCH_JOBS_FAIL'
};
